"""Register all subcommands with the top-level argument parser."""
from __future__ import annotations

from csv_surgeon.commands import (
    aggregate_cmd,
    sort_cmd,
    rename_cmd,
    dedupe_cmd,
    fill_cmd,
    cast_cmd,
    slice_cmd,
    drop_cmd,
    stats_cmd,
    pivot_cmd,
    sample_cmd,
    head_cmd,
    join_cmd,
    uniq_cmd,
    freq_cmd,
    flatten_cmd,
    explode_cmd,
    transpose_cmd,
    convert_cmd,
    reorder_cmd,
    add_col_cmd,
    merge_cmd,
    split_cmd,
    replace_cmd,
    strip_cmd,
    validate_cmd,
    format_cmd,
    diff_cmd,
    normalize_cmd,
    encode_cmd,
    rename_cols_cmd,
    truncate_cmd,
    count_cmd,
    clip_cmd,
    shift_cmd,
    round_cmd,
    bucket_cmd,
    percent_cmd,
    zscore_cmd,
    rank_cmd,
    window_cmd,
    cumsum_cmd,
    lag_cmd,
    movavg_cmd,
    corr_cmd,
    abs_cmd,
    scale_cmd,
    log_cmd,
    pow_cmd,
    interp_cmd,
    impute_cmd,
)

_COMMANDS = [
    aggregate_cmd,
    sort_cmd,
    rename_cmd,
    dedupe_cmd,
    fill_cmd,
    cast_cmd,
    slice_cmd,
    drop_cmd,
    stats_cmd,
    pivot_cmd,
    sample_cmd,
    head_cmd,
    join_cmd,
    uniq_cmd,
    freq_cmd,
    flatten_cmd,
    explode_cmd,
    transpose_cmd,
    convert_cmd,
    reorder_cmd,
    add_col_cmd,
    merge_cmd,
    split_cmd,
    replace_cmd,
    strip_cmd,
    validate_cmd,
    format_cmd,
    diff_cmd,
    normalize_cmd,
    encode_cmd,
    rename_cols_cmd,
    truncate_cmd,
    count_cmd,
    clip_cmd,
    shift_cmd,
    round_cmd,
    bucket_cmd,
    percent_cmd,
    zscore_cmd,
    rank_cmd,
    window_cmd,
    cumsum_cmd,
    lag_cmd,
    movavg_cmd,
    corr_cmd,
    abs_cmd,
    scale_cmd,
    log_cmd,
    pow_cmd,
    interp_cmd,
    impute_cmd,
]


def register_all(subparsers) -> None:
    """Attach every command's subparser to *subparsers*."""
    for cmd in _COMMANDS:
        cmd.add_subparser(subparsers)
